version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8000"
    command: bash -c "uvicorn app.main:api --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./app:/usr/src/code/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_SEND_EVENTS=True
      - CLIENT_HOST=True
      - DATABASE_URL=mysql://x1f4hjex4qztx3zsy56m:pscale_pw_LN6KC2iZxrEdVYO7pqL9nszzONg2R8JLIoJWTsCRyNI@aws.connect.psdb.cloud/deskflow-db?sslaccept=strict
      - DOPPLER_CONFIG=True
      - DOPPLER_ENVIRONMENT=True
      - DOPPLER_PROJECT=redis://redis:6379/0
      - FLOWER_UNAUTHENTICATED_API=True
      - ISSUE_CATEGORIES=deskflow-backend
      - OPENAI_API_KEY=redis://redis:6379/0
      - OPENAI_ORG_ID=org-C15lzQ0mQYcGkjGrpiBPk2Hb
      - PINECONE_API_KEY=50f995ae-f134-4a60-8aba-edf67c153790
      - PYTHON_VERSION=3.11.0
      - REDIS_DB=0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SLACK_APP_SCOPES=app_mentions:read,channels:history,channels:read,chat:write,commands,groups:history,im:history,im:read,im:write,mpim:history,users:read,users:read.email,users.profile:read
      - SLACK_APP_TOKEN=xapp-1-A0577CLLQJ3-5259851563715-62dbbc7bdda826873fb526d769d3f8becc6de894ce0968a8f0e044f938b0d6c9
      - SLACK_BOT_TOKEN=xoxb-5172579464435-5259978479138-GtvpF6j8knQeTsD1piAjK6AU
      - SLACK_CLIENT_ID=5172579464435.5245428704615
      - SLACK_CLIENT_SECRET=8293133c5c9f1b2e6b1ad32a9120b57d
      - SLACK_SIGNING_SECRET=cdf99b29e564866eccca0cc21a20e057
      - ZENDESK_API_KEY=1ASu216KqW6p0BHrBIOSAYaBlax2NmHvRu5rCAAk
      - ZENDESK_CLIENT_ID=9052958739740
    depends_on:
      - redis
  worker:
    build: .
    command: celery -A app.worker worker --loglevel=info --logfile=/code/app/logs/celery.log --uid=celery
    volumes:
      - ./app:/usr/src/app
    environment:
      - DOPPLER_ENVIRONMENT=dev
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - C_FORCE_ROOT=false
    depends_on:
      - api
      - redis
  redis:
    image: redis:7
    ports:
      - "8081:6379"
  flower:
    build: .
    command: celery -A app.worker --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - DOPPLER_ENVIRONMENT=dev
      - FLOWER_UNAUTHENTICATED_API=true
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis
    depends_on:
      - api
      - redis
      - worker