version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8000"
    command: bash -c "uvicorn app.main:api --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./app:/usr/src/code/app
    environment:
      - CELERY_BROKER_URL={{.CELERY_BROKER_URL}}
      - CELERY_RESULT_BACKEND={{.CELERY_RESULT_BACKEND}}
      - CELERY_SEND_EVENTS={{.CELERY_SEND_EVENTS}}
      - CLIENT_HOST={{.CELERY_SEND_EVENTS}}
      - DATABASE_URL={{.DATABASE_URL}}
      - DOPPLER_CONFIG={{.CELERY_SEND_EVENTS}}
      - DOPPLER_ENVIRONMENT={{.CELERY_SEND_EVENTS}}
      - DOPPLER_PROJECT={{.CELERY_RESULT_BACKEND}}
      - FLOWER_UNAUTHENTICATED_API={{.CELERY_SEND_EVENTS}}
      - ISSUE_CATEGORIES={{.DOPPLER_PROJECT}}
      - OPENAI_API_KEY={{.CELERY_RESULT_BACKEND}}
      - OPENAI_ORG_ID={{.OPENAI_ORG_ID}}
      - PINECONE_API_KEY={{.PINECONE_API_KEY}}
      - PYTHON_VERSION={{.PYTHON_VERSION}}
      - REDIS_DB={{.REDIS_DB}}
      - REDIS_HOST={{.REDIS_HOST}}
      - REDIS_PORT={{.REDIS_PORT}}
      - SLACK_APP_SCOPES={{.SLACK_APP_SCOPES}}
      - SLACK_APP_TOKEN={{.SLACK_APP_TOKEN}}
      - SLACK_BOT_TOKEN={{.SLACK_BOT_TOKEN}}
      - SLACK_CLIENT_ID={{.SLACK_CLIENT_ID}}
      - SLACK_CLIENT_SECRET={{.SLACK_CLIENT_SECRET}}
      - SLACK_SIGNING_SECRET={{.SLACK_SIGNING_SECRET}}
      - ZENDESK_API_KEY={{.ZENDESK_API_KEY}}
      - ZENDESK_CLIENT_ID={{.ZENDESK_CLIENT_ID}}
    depends_on:
      - redis
  worker:
    build: .
    command: celery -A app.worker worker --loglevel=info --logfile=/code/app/logs/celery.log --uid=celery
    volumes:
      - ./app:/usr/src/app
    environment:
      - DOPPLER_ENVIRONMENT=dev
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - C_FORCE_ROOT=false
    depends_on:
      - api
      - redis
  redis:
    image: redis:7
    ports:
      - "8081:6379"
  flower:
    build: .
    command: celery -A app.worker --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - DOPPLER_ENVIRONMENT=dev
      - FLOWER_UNAUTHENTICATED_API=true
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis
    depends_on:
      - api
      - redis
      - worker