services:
  # A Docker web service
  - type: web
    name: fastapi
    runtime: python
    repo: https://github.com/Chipzstar/DeskflowGPTBackend.git # optional
    region: frankfurt # optional (defaults to oregon)
    plan: starter # optional (defaults to starter instance type)
    branch: alfred-query-issue-tracking # optional (defaults to master)
    buildCommand: pip install -r requirements.txt && prisma py fetch && prisma py generate
    startCommand: uvicorn app.main:api --host 0.0.0.0 --port $PORT # optional (defaults to Dockerfile command)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: my_redis
          property: host # available properties are listed below
      - key: REDIS_PORT
        fromService:
          type: redis
          name: my_redis
          property: port
      - fromGroup: DeskflowAPI Dev
  # A Redis instance
  - type: redis
    name: my_redis
    region: frankfurt
    ipAllowList: # required
      - source: 0.0.0.0/0
        description: everywhere
    plan: starter # optional (defaults to starter instance type)
    maxmemoryPolicy: allkeys-lru # optional (defaults to allkeys-lru)